{% set name = "rfc6555" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rfc6555-{{ version }}.tar.gz
  sha256: 123905b8f68e2bec0c15f321998a262b27e2eaadea29a28bd270021ada411b67

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - rfc6555
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.github.com/SethMichaelLarson/rfc6555
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python implementation of the Happy Eyeballs Algorithm described in RFC 6555
  description: |
    Python implementation of the Happy Eyeballs Algorithm described
    in RFC 6555. Provided with a single file and dead-simple API to
    allow easy vendoring and integration into other projects.
  doc_url: https://www.github.com/SethMichaelLarson/rfc6555
  dev_url: https://www.github.com/SethMichaelLarson/rfc6555

extra:
  recipe-maintainers:
    - jan-janssen
